export default {

INVOICE_ID:{data:"",regex:"",required:""},
INVOICE_NO:{data:"",regex:"",required:""},
COMPANY_ID:{data:"",regex:"",required:""},
COMPANY_CONTACT_ID:{data:"",regex:"",required:""},
QUOTATION_ID:{data:"",regex:"",required:""},
QUOTATION_NO:{data:"",regex:"",required:""},
COMPANY_NAME_EN:{data:"",regex:"",required:""},
COMPANY_NAME_TH:{data:"",regex:"",required:""},
BRANCH_TYPE:{data:"",regex:"",required:""},
BRANCH_NUMBER:{data:"",regex:"",required:""},
TAX_ID:{data:"",regex:"",required:""},
INVOICE_TYPE:{data:"",regex:"",required:""},
INVOICE_DOCUMENT_BOOK:{data:"",regex:"",required:""},
INVOICE_REFERENCE:{data:"",regex:"",required:""},
INVOICE_PROJECT:{data:"",regex:"",required:""},
INVOICE_AMOUNT:{data:"",regex:"",required:""},
INVOICE_TOTALAMOUNT:{data:"",regex:"",required:""},
INVOICE_COMPANY_NAME:{data:"",regex:"",required:""},
INVOICE_BUILDING_NAME_TH:{data:"",regex:"",required:""},
INVOICE_BUILDING_NAME_EN:{data:"",regex:"",required:""},
INVOICE_FLOOR:{data:"",regex:"",required:""},
INVOICE_ADD_NO:{data:"",regex:"",required:""},
INVOICE_MOO:{data:"",regex:"",required:""},
INVOICE_SOI_TH:{data:"",regex:"",required:""},
INVOICE_SOI_EN:{data:"",regex:"",required:""},
INVOICE_ROAD_TH:{data:"",regex:"",required:""},
INVOICE_ROAD_EN:{data:"",regex:"",required:""},
INVOICE_SUB_DISTRICT_TH:{data:"",regex:"",required:""},
INVOICE_SUB_DISTRICT_EN:{data:"",regex:"",required:""},
INVOICE_DISTRICT_TH:{data:"",regex:"",required:""},
INVOICE_DISTRICT_EN:{data:"",regex:"",required:""},
INVOICE_PROVINCE_TH:{data:"",regex:"",required:""},
INVOICE_PROVINCE_EN:{data:"",regex:"",required:""},
INVOICE_POSTAL_CODE:{data:"",regex:"",required:""},
INVOICE_CONTACT_PERSON:{data:"",regex:"",required:""},
OTHER_CONTACT_PERSON:{data:"",regex:"",required:""},
DISCOUNT_TYPE:{data:"",regex:"",required:""},
DISCOUNT_BAHT:{data:"",regex:"",required:""},
DISCOUNT_PERCENT:{data:"",regex:"",required:""},
SUB_AMOUNT:{data:"",regex:"",required:""},
VAT_TYPE:{data:"",regex:"",required:""},
VAT:{data:"",regex:"",required:""},
TOTAL_AMOUNT:{data:"",regex:"",required:""},
INVOICE_CODE_AUTOFLIGHT:{data:"",regex:"",required:""},
INVOICE_REMARK:{data:"",regex:"",required:""},
INVOICE_STATUS:{data:"",regex:"",required:""},
STATUS:{data:"",regex:"",required:""},
DELETE_FLAG:{data:"",regex:"",required:""},
CREATE_DATE:{data:"",regex:"",required:""},
DUE_DATE:{data:"",regex:"",required:""},
EXPIRE_DATE:{data:"",regex:"",required:""},
UPDATE_DATE:{data:"",regex:"",required:""},
USER_ID:{data:"",regex:"",required:""},
	
	//Interface
	COMPANY_CONTACT_FIRST_NAME_EN:SELECT_CONTACT_PERSON.data.filter((ele)=>ele.COMPANY_CONTACT_ID==SELECT_INVOICE.data[0].COMPANY_CONTACT_ID)[0].COMPANY_CONTACT_FIRST_NAME_EN,
	COMPANY_CONTACT_FIRST_NAME_TH:SELECT_CONTACT_PERSON.data.filter((ele)=>ele.COMPANY_CONTACT_ID==SELECT_INVOICE.data[0].COMPANY_CONTACT_ID)[0].COMPANY_CONTACT_FIRST_NAME_TH,
	COMPANY_CONTACT_SUR_NAME_EN:SELECT_CONTACT_PERSON.data.filter((ele)=>ele.COMPANY_CONTACT_ID==SELECT_INVOICE.data[0].COMPANY_CONTACT_ID)[0].COMPANY_CONTACT_SUR_NAME_EN,
	COMPANY_CONTACT_SUR_NAME_TH:SELECT_CONTACT_PERSON.data.filter((ele)=>ele.COMPANY_CONTACT_ID==SELECT_INVOICE.data[0].COMPANY_CONTACT_ID)[0].COMPANY_CONTACT_SUR_NAME_TH,
	
	//View
	COMPANY_NAME:	{data:this.COMPANY_NAME_TH.data||this.COMPANY_NAME_EN.data,regex:"",required:this.COMPANY_NAME_TH.required||this.COMPANY_NAME_EN.required},
	COMPANY_CONTACT:{data:this.COMPANY_CONTACT_ID.data,regex:"",required:this.COMPANY_CONTACT_ID.required},
	COMPANY_CONTACT_EMAIL:{data:!COMPANY_CONTACT.selectedOptionValue?"": SELECT_CONTACT_PERSON.data.filter((ele)=>ele.COMPANY_CONTACT_ID==COMPANY_CONTACT.selectedOptionValue)[0].COMPANY_CONTACT_EMAIL,regex:"",required:false},
	COMPANY_CONTACT_TELEPHONE:{data:!COMPANY_CONTACT.selectedOptionValue?"":SELECT_CONTACT_PERSON.data.filter((ele)=>ele.COMPANY_CONTACT_ID==COMPANY_CONTACT.selectedOptionValue)[0].COMPANY_CONTACT_TELEPHONE,regex:"",required:false},
}