export default {
INVENTORY_ID: {...INVENTORY_ID, data: INVENTORY_ID.text},
//PRODUCT_ID: {...PRODUCT_ID, data: PRODUCT_ID.text},
INVENTORY_NAME: {...INVENTORY_NAME, data: INVENTORY_NAME.text},
METER_ID: {...METER_ID, data: METER_ID.text},
FLOOR_NO: {...FLOOR_NO, data: FLOOR_NO.selectedOptionValue},
PRODUCT_DESCRIPTION: {...PRODUCT_DESCRIPTION, data: PRODUCT_DESCRIPTION.text},
ZONE: {...ZONE, data: ZONE.selectedOptionValue},
QUANTITY: {...QUANTITY, data: QUANTITY.text},
CT: {...CT, data: CT.selectedOptionValue},
START_UNIT: {...START_UNIT, data: START_UNIT.text},
DIGIT_LENGTH: {...DIGIT_LENGTH, data: DIGIT_LENGTH.text},
DECIMAL_POINT: {...DECIMAL_POINT, data: DECIMAL_POINT.text},
MINIMUM_UNIT: {...MINIMUM_UNIT, data: MINIMUM_UNIT.text},
MAXIMUM_UNIT: {...MAXIMUM_UNIT, data: MAXIMUM_UNIT.text},
AVERAGE_UNIT: {...AVERAGE_UNIT, data: AVERAGE_UNIT.text},
PRICE_PER_UNIT: {...PRICE_PER_UNIT, data: (PRICE_PER_UNIT.value!=undefined?PRICE_PER_UNIT.value:"").toString()},
START_DATE: {...START_DATE, data: START_DATE.selectedDate},
END_DATE: {...END_DATE, data: END_DATE.selectedDate},
STATUS: {...STATUS, data: STATUS.selectedOptionValue},
SHARED: {...SHARED, data: SHARED.isChecked},
PERCENTAGE: {...PERCENTAGE, data: PERCENTAGE.text},
ACCOUNTING_DESCRIPTION:{...ACCOUNTING_DESCRIPTION,data : ACCOUNTING_DESCRIPTION.text},
	SUBMETER_ID:{...SUB_INVENTORY,data : SUB_INVENTORY.text},
	FLOOR_ENABLE:{...FLOOR_ENABLE,data : FLOOR_ENABLE.isChecked},
	UOM:{...UOM,data : UOM.selectedOptionValue},
}