export default {
	//BILLING_REMARK_ID:{...BILLING_REMARK_ID,data:""},
	COMPANY_ID:{...COMPANY_ID,data:COMPANY_ID.text||"TEMP"},
	//BILLING_REMARK_TYPE:{...BILLING_REMARK_TYPE,data:""},
	INVOICE_REMARK_TYPE:{...INVOICE_REMARK_TYPE,data:INVOICE_REMARK_TYPE.selectedOptionValue||""},
	BILLING_REMARK_PRODUCT_TYPE_ID:{...REMARK_PRODUCT_TYPE_NAME,data:INVOICE_REMARK_TYPE.selectedOptionValue===Configs.INVOICE_REMARK_TYPE.PRODUCT?REMARK_PRODUCT_TYPE_NAME.selectedOptionValue:""},
	BILLING_REMARK_PRODUCT_TYPE_NAME:{...REMARK_PRODUCT_TYPE_NAME,data:INVOICE_REMARK_TYPE.selectedOptionValue===Configs.INVOICE_REMARK_TYPE.PRODUCT?REMARK_PRODUCT_TYPE_NAME.selectedOptionLabel:""},
	BILLING_REMARK_GROUP_ID:{...BILLING_REMARK_GROUP_ID,data:INVOICE_REMARK_TYPE.selectedOptionValue===Configs.INVOICE_REMARK_TYPE.GROUP?BILLING_REMARK_GROUP_ID.text:""},
	BILLING_REMARK_DETAIL:{...BILLING_REMARK_DETAIL,data:BILLING_REMARK_DETAIL.text||""},
	
}