export default {
  //COMPANY_PROFILE_ID: {...COMPANY_PROFILE_ID, data: COMPANY_PROFILE_ID},
  COMPANY_ID: {...COMPANY_ID, data: COMPANY_ID.text},
  COMPANY_PROFILE_AGREEMENT_NO: {...AGREEMENT_ID, data: AGREEMENT_ID.selectedOptionValue},
  COMPANY_PROFILE_PERIOD_START: {...COMPANY_PROFILE_PERIOD_START, data: COMPANY_PROFILE_PERIOD_START.selectedDate},
  COMPANY_PROFILE_PERIOD_END: {...COMPANY_PROFILE_PERIOD_END, data: COMPANY_PROFILE_PERIOD_END.selectedDate},
  FORMULA_ID: {...FORMULA, data: FORMULA.selectedOptionValue},
  //STATUS: {...STATUS, data: STATUS},
  //CREATE_DATE: {...CREATE_DATE, data: CREATE_DATE},
  //UPDATE_DATE: {...UPDATE_DATE, data: UPDATE_DATE},
  //INVENTORY_ID: {...INVENTORY_ID, data: INVENTORY_ID},
  PROFILE_FLOOR_MODIFIER: {...COMPANY_PROFILE_FLOOR_NO, data: COMPANY_PROFILE_FLOOR_NO.text},
  PROFILE_PP_UNIT_MODIFIER: {...PRICE_PER_UNIT, data: PRICE_PER_UNIT.value},
	QUANTITY:{...QUANTITY,data:QUANTITY.text}
}
