export default {
	userSession:"userSession",
	permissions:{VIEW:"INVV",EDIT:"INVE"},
	forceKick:false,
	forceLogin:false,
	errorAlert:"",
	pageName:"Invoice Detail",
	BodyInit:"VIEW",
	dateFormat:"DD MMMM YYYY",
	INVOICE_ID:"INVOICE_ID",
	COMPANY_ID:"COMPANY_ID",
	COMPANY_CONTACT_ID:"COMPANY_CONTACT_ID",
	BILLING_INFORMATION_ID:"BILLING_INFORMATION_ID",
	Invoice_type:{NON_VAT:"Non-VAT",VAT:"VAT",currentType: ""},
	invoice_items:[{"Description":"-","Quantity":"-","Unit Price":"-","Amount":"-"}],
	requiredColorAlert:"#ef4444",
	requiredColorPass:"",
}