export default {
	userSession:"userSession",
	permissions:{VIEW:"INVV",EDIT:"INVE",SHOW_INVOICE_EXECUTE:"INEX",SHOW_INVONCE_CN:"INCN"},
	forceKick:false,
	forceLogin:false,
	errorAlert:"",
	invoiceIDParameterName:"InvoiceNumber",
	pageName:"Invoice Detail",
	BodyInit:"LOADING",
	dateFormat:"D MMM YYYY",
	INVOICE_ID:"INVOICE_NO",
	COMPANY_ID:"COMPANY_ID",
	COMPANY_CONTACT_ID:"COMPANY_CONTACT_ID",
	BILLING_INFORMATION_ID:"BILLING_INFORMATION_ID",
	Invoice_type:{NON_VAT:"Non-VAT",VAT:"VAT",currentType: ""},
	invoice_items:null,
	requiredColorAlert:"#ef4444",
	requiredColorPass:"",
	is_draft:SELECT_INVOICE.data[0]?.STATUS === "Draft Invoice",
	edit_item:false,
	removeDetails_ID:[],
	editDetails_ID:[],
	undo_stack:{data:[],type:{"remove":0,"edit":1}}
}