export default {
BILLING_INFORMATION_ID:{data:"",regex:"",required:"",color:""},
BILLING_INFORMATION_TYPE:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_TYPE_NAME:{data:"",regex:"",required:"",color:""},
BILLING_TITLE_PREFIX:{data:"",regex:"",required:"",color:""},
BILLING_TITLE_PREFIX_OTHER:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_NAME_EN:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_NAME_TH:{data:"",regex:"",required:"",color:""},
BILLING_SUFFIX:{data:"",regex:"",required:"",color:""},
BILLING_BRANCH_TYPE:{data:"",regex:"",required:"",color:""},
BILLING_BRANCH_NUMBER:{data:"",regex:"",required:"",color:""},
BILLING_SHOP_NAME:{data:"",regex:"",required:"",color:""},
BILLING_TELEPHONE:{data:"",regex:"",required:"",color:""},
BILLING_CONTACT_EMAIL:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_BUSINESS_TYPE_EN:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_BUSINESS_TYPE_TH:{data:"",regex:"",required:"",color:""},
BILLING_FAX:{data:"",regex:"",required:"",color:""},
BILLING_TAX_ID:{data:"",regex:"",required:"",color:""},
BILLING_WEBSITE:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_BUILDING_NAME_EN:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_BUILDING_NAME_TH:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_FLOOR:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_ADD_NO:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_MOO:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_SOI_EN:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_SOI_TH:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_ROAD_EN:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_ROAD_TH:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_SUB_DISTRICT_EN:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_SUB_DISTRICT_TH:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_DISTRICT_EN:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_DISTRICT_TH:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_PROVINCE_EN:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_PROVINCE_TH:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_POSTAL_CODE:{data:"",regex:"",required:"",color:""},
BILLING_COMPANY_CODE:{data:"",regex:"",required:"",color:""},
CREDIT_TERM:{data:"",regex:"",required:"",color:""},
REMARK_OF_INVOICE:{data:"",regex:"",required:"",color:""},
REMARK_OF_RECEIPT:{data:"",regex:"",required:"",color:""},
STATUS:{data:"Active",regex:"",required:"",color:""},
CREATE_DATE:{data:"",regex:"",required:"",color:""},
CREDIT_DAY:{data:"",regex:"",required:"",color:""},
	
	//interface
BILLING_SUB_DISTRICT_TH:{data:this.BILLING_COMPANY_SUB_DISTRICT_TH.data,
												 regex:this.BILLING_COMPANY_SUB_DISTRICT_TH.regex,
												 required:this.BILLING_COMPANY_SUB_DISTRICT_TH.required||this.BILLING_COMPANY_SUB_DISTRICT_EN.required,
												 color:(this.BILLING_COMPANY_SUB_DISTRICT_TH.color==Configs.requiredColorAlert||this.BILLING_COMPANY_SUB_DISTRICT_EN.color==Configs.requiredColorAlert)?Configs.requiredColorAlert:Configs.requiredColorPass},
	
BILLING_DISTRICT_TH:{data:this.BILLING_COMPANY_DISTRICT_TH.data,
										 regex:this.BILLING_COMPANY_DISTRICT_TH.regex,
										 required:this.BILLING_COMPANY_DISTRICT_TH.required||this.BILLING_COMPANY_DISTRICT_EN.required,
										 color:(this.BILLING_COMPANY_DISTRICT_TH.color==Configs.requiredColorAlert||this.BILLING_COMPANY_DISTRICT_EN.color==Configs.requiredColorAlert)?Configs.requiredColorAlert:Configs.requiredColorPass},
	
BILLING_PROVINCE_TH:{data:this.BILLING_COMPANY_PROVINCE_TH.data,
										 regex:this.BILLING_COMPANY_PROVINCE_TH.regex,
										 required:this.BILLING_COMPANY_PROVINCE_TH.required||this.BILLING_COMPANY_PROVINCE_EN.required,
										 color:(this.BILLING_COMPANY_PROVINCE_TH.color==Configs.requiredColorAlert||this.BILLING_COMPANY_PROVINCE_EN.color==Configs.requiredColorAlert)?Configs.requiredColorAlert:Configs.requiredColorPass},
	
BILLING_POSTAL_CODE:{data:this.BILLING_COMPANY_POSTAL_CODE.data,
										 regex:this.BILLING_COMPANY_POSTAL_CODE.regex,
										 required:this.BILLING_COMPANY_POSTAL_CODE.required,
										 color:this.BILLING_COMPANY_POSTAL_CODE.color},

BCOMPANY_BUILDING_NAME_EN:{data:this.BILLING_COMPANY_BUILDING_NAME_EN.data,
													 regex:this.BILLING_COMPANY_BUILDING_NAME_EN.regex,
													 required:this.BILLING_COMPANY_BUILDING_NAME_EN.required,
													 color:this.BILLING_COMPANY_BUILDING_NAME_EN.color},
BCOMPANY_BUILDING_NAME_TH:{data:this.BILLING_COMPANY_BUILDING_NAME_TH.data,
													 regex:this.BILLING_COMPANY_BUILDING_NAME_TH.regex,
													 required:this.BILLING_COMPANY_BUILDING_NAME_TH.required,
													 color:this.BILLING_COMPANY_BUILDING_NAME_TH.color},
BILLING_COMPANY_BUSINESS_TYPE:{data:_.trim((this.BILLING_COMPANY_BUSINESS_TYPE_TH.data||"")+"/"+(this.BILLING_COMPANY_BUSINESS_TYPE_EN.data||""),"/"),
															 regex:"",
															 required:this.BILLING_COMPANY_BUSINESS_TYPE_TH.required||this.BILLING_COMPANY_BUSINESS_TYPE_EN.required,
															 color:(this.BILLING_COMPANY_BUSINESS_TYPE_TH.color==Configs.requiredColorAlert||this.BILLING_COMPANY_BUSINESS_TYPE_EN.color==Configs.requiredColorAlert)?Configs.requiredColorAlert:Configs.requiredColorPass},

}